### ISSUE TITLE
500 error on querying a db

### ISSUE THREAD

**Issue by Neobii** [VeliovGroup/Meteor-Leaderboard-Neo4j#20]
This is my stack trace, it says it connects to the db successfully, is this because of some authentication setting?

Exception in callback of async function: Error: Meteor.N4JDB.query: [Meteor.neo4j.run]: Error: [object Object],706e6684ce512115c87cd4757a306d1704def3e953115762f6b67bb8c0a90950,MATCH (a:Player) RETURN a ORDER BY a.score DESC,,Wed May 06 2015 14:13:02 GMT-0400 (EDT) [500]
I20150506-14:13:02.320(-4)?     at packages/ostrio:neo4jreactivity/ostrio:neo4jreactivity_driver.coffee:524:21
I20150506-14:13:02.320(-4)?     at packages/ostrio:neo4jreactivity/ostrio:neo4jreactivity_driver.coffee:7:12
I20150506-14:13:02.320(-4)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
W20150506-14:13:02.323(-4)? (STDERR) 
W20150506-14:13:02.327(-4)? (STDERR) Error: [object Object]
=> Exited with code: 8

**Comment by Neobii** [comment]
Okay it was an authentication problem, it seems like my default neo4j install doesn't allow non authenticated queries... we should make it a lot more obvious that is what is going on, but that is an issue for the driver.

**Comment by dr-dimitru** [comment]
@Neobii Hi, sorry for late response (I've took vacation)
So... Any suggestions from your end, how to make auth problem a lot more obvious?

**Comment by dr-dimitru** [comment]
@Neobii fixed in [v0.2.13](https://github.com/VeliovGroup/ostrio-neo4jdriver/releases/tag/v0.2.13)
