### ISSUE TITLE
GraphQL Implementation

### ISSUE THREAD

**Issue by AdamBrodzinski** [VeliovGroup/Meteor-Leaderboard-Neo4j#25]
I was just wondering if you've thought about adding a branch with a GraphQL query? It looks like there's a babel plugin that can transpile it to JSON which could be passed to the publication :smile: 
https://github.com/ooflorent/babel-plugin-graphql

**Comment by dr-dimitru** [comment]
@AdamBrodzinski Didn't get your point, GraphQL is completely different technology from Neo4j

**Comment by AdamBrodzinski** [comment]
Yea perhaps I need to look into this more but I was hoping it would be possible to take the parsed GraphQL JSON and feed it into the publication, which could then use the JSON values in the Cypher query.

**Comment by dr-dimitru** [comment]
@AdamBrodzinski what the mission target?
