### ISSUE TITLE
Why duplicate nodes?

### ISSUE THREAD

**Issue by daveeel** [VeliovGroup/Meteor-Leaderboard-Neo4j#28]
Tried adding new players in the demo, checked with neo4j browser that every new player got added twice, one with ":Player" label, one without. Deletion of a player will also delete the duplication. Is it a bug or by design?

Thanks.

**Comment by dr-dimitru** [comment]
Hello @daveeel ,

Sorry for answering almost after a 3 years later.
Somehow I've missed it.

Feel free to reopen it in case if the issue is still persists on your end.
