### ISSUE TITLE
TypeError: Cannot call method 'SHA256' of undefined

### ISSUE THREAD

**Issue by dr-dimitru** [VeliovGroup/Meteor-Leaderboard-Neo4j#3]
Please refer to: [issue on Neo4jReactivity](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/issues/10)

To solve this issue simply run (inside meteor's project folder):

``` bash
meteor add sha
```

**Comment by lifeinchords** [comment]
thumbsup
