### ISSUE TITLE
Autopublish

### ISSUE THREAD

**Issue by lifeinchords** [VeliovGroup/Meteor-Leaderboard-Neo4j#6]
I20150116-06:52:22.963(-5)? *\* You've set up some data subscriptions with Meteor.publish(), but
I20150116-06:52:23.167(-5)? *\* you still have autopublish turned on. Because autopublish is still
I20150116-06:52:23.168(-5)? *\* on, your Meteor.publish() calls won't have much effect. All data
I20150116-06:52:23.168(-5)? *\* will still be sent to all clients.
I20150116-06:52:23.169(-5)? **
I20150116-06:52:23.169(-5)? *\* Turn off autopublish by removing the autopublish package:
I20150116-06:52:23.169(-5)? **
I20150116-06:52:23.169(-5)? *\*   $ meteor remove autopublish
I20150116-06:52:23.169(-5)? **
I20150116-06:52:23.169(-5)? *\* .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150116-06:52:23.169(-5)? *\* for each collection that you want clients to see.
I20150116-06:52:23.170(-5)?

Is this intended?

**Comment by dr-dimitru** [comment]
Yes, that's absolutely fine for development stage.

**Comment by lifeinchords** [comment]
great
