### ISSUE TITLE
Couldn't figure out how to change the db url

### ISSUE THREAD

**Issue by ghost** [VeliovGroup/Meteor-Leaderboard-Neo4j#8]
i want to change the server from `localhost:7474` to `user:pass@server.com:1234` - where do i set it?

**Comment by dr-dimitru** [comment]
Change property `connectionURL` of `neo4j` object:

``` javascript
neo4j.connectionURL = 'user:pass@server.com:1234';
```

For more see: https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j/blob/master/lib/neo4j.js#L4

**Comment by dr-dimitru** [comment]
@ameernuri did my answer helped you?

**Comment by ghost** [comment]
nope. it's still connecting to localhost:7474

**Comment by dr-dimitru** [comment]
Please, run:
`meteor update`

Inside project’s folder, let me know if it fix all the things

**Comment by ghost** [comment]
still not working

here's `neo4j.js`:

``` javascript
/* Allow client query execution */
neo4j.allowClientQuery = true;

neo4j.connectionURL = 'http://inklin:pass@inklin.sb02.stations.graphenedb.com:24789';

/* But deny all writing actions on client */
if(Meteor.isClient){
    neo4j.set.deny(neo4j.rules.write);
}
```

**Comment by dr-dimitru** [comment]
@ameernuri yes, it's bug.
While it's not fixed, please use environment variable: `NEO4J_URL` or `GRAPHENEDB_URL` so it will be automatically picked up by our driver

**Comment by dr-dimitru** [comment]
@ameernuri fixed in: https://github.com/VeliovGroup/ostrio-Neo4jreactivity/pull/13
